### ISSUE TITLE
Fix on tutorial

### ISSUE THREAD

**Issue by alvarezGarciaMarcos** [comunica/Tutorial-Solid-GraphQL-LD-Profile-Viewer#2]
In the authentication part of the tutorial, when you display code in the App.js component, the link to the popup (taking into account it is in the public directory) has to be "/popup" instead of "popup" as you have on your code.

**Comment by rubensworks** [comment]
I just looked into this, and this probably depends on your routers.
In this case, without the slash will work, as it is a relative URL to the popup file at the same level.

Thanks in any case for the issue!
